#!/bin/sh

set -u

cryptname="${1}"
max_tries=5
unlocked=1
base_errmsg="Passphrase was incorrect. ? attempts to unlock remaining."
shutdownmsg="Too many attempts to unlock, shutting down ..."

power_off() {
	echo "o" > /proc/sysrq-trigger
}

pre_suspend() {
	# Start udev from initramfs
	/usr/lib/systemd/systemd-udevd --daemon --resolve-names=never &>/dev/null

	# run dummy cryptsetup to make sure we have all the needed kernel modules
	# loaded before doing an actual suspend
	[ -z "${cryptname}" ] || cryptsetup luksOpen "${cryptname}" --test-passphrase &>/dev/null || :

	# Synchronize filesystems before luksSuspend
	sync

	# Lock root volume
	[ -z "${cryptname}" ] || cryptsetup luksSuspend "${cryptname}"
}

resume() {
	if [ -z "${cryptname}" ] ; then
		return
	fi
	i=0 ; while [ $i -lt $max_tries ] ; do
		clear
		if [ $i -gt 0 ] ; then
			errmsg=`echo ${base_errmsg} | sed -e "s:\?:$((max_tries-i)):"`
			echo $errmsg
		fi
		cryptsetup luksResume "${cryptname}" --tries=1 2>/dev/null
		if [ $? -eq 0 ] ; then
			unlocked=0
			break
		fi
		i=$((i+1))
   done
	if [ $unlocked -eq 1 ] ; then
		clear
		echo $shutdownmsg
		sleep 1
		power_off
	fi
}


pre_suspend

# Suspend the system
echo mem > /sys/power/state

# Resume root device
resume
